version: "3.8"

services:
  react-ui:
    build:
      context: ./
    ports:
      - "5173:5173"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
