version: '3.8'
services:
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"