name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        env:
          VITE_AUTH_ENDPOINT: ${{ secrets.VITE_AUTH_ENDPOINT }}
          VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
        run: |
          npm install
          mv node_modules/react-secure-storage/dist/types.d.ts node_modules/react-secure-storage/dist/types.ts
          sed -i '2d' node_modules/@svgr/core/dist/index.d.ts
          sed -i 's/svgoConfig?: OptimizeOptions/svgoConfig?: Options/g' node_modules/@svgr/core/dist/index.d.ts
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
